### ISSUE TITLE
set_value()

### ISSUE THREAD

**Issue by hosseinsalemi** [Patroklo/codeigniter3.x-extended-rules#1]
How can I use set_value() in HTML form?

**Comment by Patroklo** [comment]
What's the problem exactly?

**Comment by h16d** [comment]
I want to use set_value() for HTML input file form after return false form validation. When form validation return false, file path at input file form will lose.

Can I solve this problem like this?
`<input type="file" name="image" value"<?=set_value('image')?>">`

**Comment by Patroklo** [comment]
Don't have any codeigniter with that library installed, I'll try to install one for tomorrow and check it, BUT, if it doesn't return that set_value boolean, it will return an array with the $_FILE data as I'm reading at the code.

Can you make a var_dump of that set_value to check that out?

Thanks!

**Comment by h16d** [comment]
Thanks a lot!
`var_dump(set_value('image'));`
Result:
`string '1.jpg' (length=5)`
