### ISSUE TITLE
file_required and file_size_max not working

### ISSUE THREAD

**Issue by paulcanning** [Patroklo/codeigniter3.x-extended-rules#5]
If I use `file_required`, and choose a file in my form, but have other errors, I see an error saying the file is required still..

I also tried to set `file_size_max[20]` (20kb I assume, docs do not say size type) and I selected a larger file, but it gave no errors.

Any help?

**Comment by Patroklo** [comment]
Didn't use form_open_multipart? Is there something wrong in the library?
